eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: employeeservice

management:
  endpoint:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS